Avoid propagating AttributeError
flake8 will catch an AttributeError and do the wrong thing, so we should
wrap any exception that we throw in our own exception class.

If we accidentally raise an AttributeError, we start getting bogus
errors of the form:
TypeError: 'VetPlugin' object is not iterable
that mask the real error.